In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Coviddataset.csv')

In [3]:
df.head()

Fever  Bodypain  Age  RunnyNose  DiffBreath  InfectionProb
0  101.627771         1   13          1           1              1
1  101.705676         0   90          0          -1              0
2   99.201287         1   19          0           0              0
3  101.169177         1   12          0           1              0
4   98.286701         1   62          0          -1              0

In [4]:
df.tail()

Fever  Bodypain  Age  RunnyNose  DiffBreath  InfectionProb
1330  100.531711         1   15          1          -1              1
1331   99.185692         0   83          0           0              0
1332   98.090852         1   39          1           1              1
1333   98.138591         1   86          1          -1              1
1334  100.822486         0    2          1           1              0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1335 entries, 0 to 1334
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fever          1335 non-null   float64
 1   Bodypain       1335 non-null   int64  
 2   Age            1335 non-null   int64  
 3   RunnyNose      1335 non-null   int64  
 4   DiffBreath     1335 non-null   int64  
 5   InfectionProb  1335 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 62.7 KB


In [6]:
df['DiffBreath'].value_counts()

 0    458
-1    451
 1    426
Name: DiffBreath, dtype: int64

In [7]:
df.describe()

Fever     Bodypain          Age    RunnyNose   DiffBreath  \
count  1335.000000  1335.000000  1335.000000  1335.000000  1335.000000   
mean     99.948382     0.485393    50.005993     0.480899    -0.018727   
std       1.162971     0.499974    28.966454     0.499822     0.810599   
min      98.001431     0.000000     1.000000     0.000000    -1.000000   
25%      98.916928     0.000000    25.000000     0.000000    -1.000000   
50%      99.924037     0.000000    49.000000     0.000000     0.000000   
75%     100.952667     1.000000    75.000000     1.000000     1.000000   
max     101.996077     1.000000   100.000000     1.000000     1.000000   

       InfectionProb  
count    1335.000000  
mean        0.474906  
std         0.499557  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

## Train test split

In [8]:
# def data_split(data,ratio):
#     np.random.seed(42)
#     shuffled = np.random.permutation(len(data))
#     test_set_size = int(len(data)*ratio)
#     test_indices = shuffled[:test_set_size]
#     train_indices = shuffled[test_set_size:]
#     return data.iloc[train_indices], data.iloc[test_indices]

In [9]:
# train, test = data_split(df,0.2)
X = df.iloc[:,:-1].values
y = df.iloc[:, -1].values
print(X)
print(y)

[[101.62777117   1.          13.           1.           1.        ]
 [101.70567646   0.          90.           0.          -1.        ]
 [ 99.20128749   1.          19.           0.           0.        ]
 ...
 [ 98.0908523    1.          39.           1.           1.        ]
 [ 98.13859052   1.          86.           1.          -1.        ]
 [100.82248601   0.           2.           1.           1.        ]]
[1 0 0 ... 1 1 0]


In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)

[[ 1.44459257  1.02965294 -1.27802529  1.03896066  1.25722911]
 [ 1.51160585 -0.97120103  1.38121827 -0.96250035 -1.21100745]
 [-0.64264226  1.02965294 -1.0708115  -0.96250035  0.02311083]
 ...
 [-1.59782652  1.02965294 -0.38009889  1.03896066  1.25722911]
 [-1.55676263  1.02965294  1.24307575  1.03896066 -1.21100745]
 [ 0.75189505 -0.97120103 -1.65791722  1.03896066  1.25722911]]


In [29]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 40)
print(X_train)

[[-0.67776378  1.02965294  1.13946885 -0.96250035 -1.21100745]
 [ 0.33238453 -0.97120103 -0.69091957 -0.96250035  0.02311083]
 [-0.52154028 -0.97120103 -0.51824141  1.03896066 -1.21100745]
 ...
 [ 1.02879574  1.02965294 -1.24348966  1.03896066  0.02311083]
 [ 0.40730641 -0.97120103 -0.41463452 -0.96250035  0.02311083]
 [-0.79597039 -0.97120103  1.69203894 -0.96250035  1.25722911]]


In [30]:
# X_train = train[['Fever', 'Bodypain','Age','RunnyNose','DiffBreath']].to_numpy()
# X_test = test[['Fever', 'Bodypain','Age','RunnyNose','DiffBreath']].to_numpy()

In [31]:
# Y_train = train[['InfectionProb']].to_numpy().reshape(1067)
# Y_test = test[['InfectionProb']].to_numpy().reshape(267,)

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

In [33]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [38]:
ip = [102, 1, 22, -1, 1]
# here we get array as an output[[]] so we write [0][1]
infecprob = lr.predict_proba([ip])[0][1]

In [39]:
infecprob

0.8679996839522839

In [40]:
y_pred = lr.predict(X_test)

In [41]:
import sklearn.metrics as met
mse = met.mean_squared_error(y_test,y_pred)
print('MSE :', mse)
r2 = met.r2_score(y_test,y_pred)
print('R-Square_score :', r2)
rmse = np.sqrt(mse)
print('RMSE :', rmse)

MSE : 0.48314606741573035
R-Square_score : -0.9404507042253525
RMSE : 0.6950870934032154
